[package]
name = "rasn-compiler-tests"
version = "0.1.0"
edition = "2021"

[lib]

[dependencies]
rasn-compiler-derive = { path = "../rasn-compiler-derive" }
rasn-compiler = { path = "../rasn-compiler" }
rasn = { git = "https://github.com/XAMPPRocky/rasn" }

[dev-dependencies]
bitvec = { version = "1" }
bitvec-nom = { version = "0.2" }
bnf = "0.5.0"
rasn-kerberos = "0.10.0"
bytes = "1.4.0"
num-bigint = "0.4.4"

